spring.application.name=demo
# هذا السطر يجعل السبرينغ ينشئ جداول المنتجات تلقائياً
spring.jpa.hibernate.ddl-auto=update
spring.security.user.name=admin
spring.security.user.password=1234
# هذا السطر يظهر لكِ في الأسفل كل ما يحدث في قاعدة البيانات
spring.jpa.show-sql=true
spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}