# 1. الاتصال المباشر بقاعدة البيانات بكلمة المرور الخاصة بكِ 1234
spring.datasource.url=jdbc:mysql://junction.proxy.rlwy.net:56644/railway
spring.datasource.username=root
spring.datasource.password=1234

# 2. إعدادات السيرفر والـ Driver
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# 3. تحديد المحرك الصحيح لقاعدة البيانات لـ Hibernate الحديث
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect